apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
  ports:
    - name: "http"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.mlfow_server_image.port }}
      protocol: "TCP"
