---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mlflow-config"
data:
  artifacts_store_uri: "gs://artifacts-4238717282752847c3d58ebe"
  sql_instance_connection_name: "ai-mlflow-01:europe-west3:mlflow-backend"
