---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mlflow-config"
data:
  artifacts_store_uri: "gs://optimisation-mlflow/artifacts"
  sql_instance_connection_name: "development-env-ta:europe-west1:optimisation-mlflow"
